apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "prisma.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "prisma.name" . }}
    helm.sh/chart: {{ include "prisma.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "prisma.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "prisma.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          volumeMounts:
          {{- if .Values.vhost }}
            - name: nginx-vhost
              mountPath: /etc/nginx/conf.d/
          {{- end }}
          {{- if .Values.htpasswd }}
            - name: nginx-htpasswd
              mountPath: /etc/nginx/htpasswd/
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      volumes:
      {{- if .Values.vhost }}
        - name: nginx-vhost
          configMap:
            name: {{ include "prisma.fullname" . }}
      {{- end }}
      {{- if .Values.htpasswd }}
        - name: nginx-htpasswd
          configMap:
            name: {{ include "prisma.fullname" . }}-htpasswd
      {{- end }}
